export const RECEIVE_TEAMS = 'RECEIVE_TEAMS';
export const RECEIVE_PICK_VALUES_BAYESIAN = 'RECEIVE_PICK_VALUE_BAYESIAN';
export const RECEIVE_DRAFTS = 'RECEIVE_DRAFTS';
export const RECEIVE_PICKS = 'RECEIVE_PICKS';
export const RECEIVE_ADP = 'RECEIVE_ADP';
export const RECEIVE_PLAYERS = 'RECEIVE_PLAYERS';
export const SELECT_TEAM = 'SELECT_TEAM';
