export const RECEIVE_TEAMS = 'RECEIVE_TEAMS';
export const RECEIVE_PICK_VALUES_BAYESIAN = 'RECEIVE_PICK_VALUE_BAYESIAN';
export const RECEIVE_DRAFTS = 'RECEIVE_DRAFTS';
export const SELECT_DRAFT = 'SELECT_DRAFT';
export const MAP_PICKS = 'MAP_PICKS';
export const RECEIVE_PICKS = 'RECEIVE_PICKS';
export const SELECT_PICK = 'SELECT_PICK';

export const SELECT_TEAM = 'SELECT_TEAM';
export const SELECT_RECEIVING_TEAM = 'SELECT_RECEIVING_TEAM';

export const RECEIVE_ADP = 'RECEIVE_ADP';
export const RECEIVE_PLAYERS = 'RECEIVE_PLAYERS';

export const RECEIVE_TRADES = 'RECEIVE_TRADES';
export const CREATE_TRADE = 'CREATE_TRADE';
export const ADD_GIVING_TEAM_PICK = 'ADD_GIVING_TEAM_PICK';
export const ADD_RECEIVING_TEAM_PICK = 'ADD_RECEIVING_TEAM_PICK';
export const REMOVE_GIVING_TEAM_PICK = 'REMOVE_GIVING_TEAM_PICK';
export const REMOVE_RECEIVING_TEAM_PICK = 'REMOVE_RECEIVING_TEAM_PICK';
export const CLEAR_RECEIVING_TEAM = 'CLEAR_RECEIVING_TEAM';
export const CLEAR_TRADE = 'CLEAR_TRADE';
export const SAVE_TRADE = 'SAVE_TRADE';
export const LOAD_TRADE = 'LOAD_TRADE';
