// Auth
export const CREATE_SESSION = 'CREATE_SESSION';
export const DESTROY_SESSION = 'DESTROY_SESSION';
export const INVALID_SESSION = 'INVALID_SESSION';
export const CLEAR_AUTH_MESSAGES = 'CLEAR_AUTH_MESSAGES';
export const PASSWORD_RESET_EMAIL_SENT = 'PASSWORD_RESET_EMAIL_SENT';

// Generic
export const CAUGHT_ERROR = 'CAUGHT_ERROR';

// Users (teams)
export const RECEIVE_USERS = 'RECEIVE_USERS';

// Drafts
export const FETCHING_DRAFTS = 'FETCHING_DRAFTS';
export const FETCHED_DRAFTS = 'FETCHED_DRAFTS';
export const RECEIVE_DRAFTS = 'RECEIVE_DRAFTS';
export const SELECT_DRAFT = 'SELECT_DRAFT';
export const MAP_PICKS = 'MAP_PICKS';
export const RECEIVE_PICKS = 'RECEIVE_PICKS';
export const SELECT_PICK = 'SELECT_PICK';

// Bayesian pick values
export const RECEIVE_PICK_VALUES_BAYESIAN = 'RECEIVE_PICK_VALUE_BAYESIAN';

// Team currently highlighted on the site, purely used for UI
export const SELECT_TEAM = 'SELECT_TEAM';

// Player and ADP data
export const RECEIVE_ADP = 'RECEIVE_ADP';
export const RECEIVE_PLAYERS = 'RECEIVE_PLAYERS';

// Trades
export const SELECT_GIVING_TEAM = 'SELECT_RECEIVING_TEAM';
export const SELECT_RECEIVING_TEAM = 'SELECT_RECEIVING_TEAM';
export const RECEIVE_USER_TRADES = 'RECEIVE_USER_TRADES';
export const RECEIVE_USER_TRADE = 'RECEIVE_USER_TRADE';
export const CREATE_TRADE = 'CREATE_TRADE';
export const ADD_GIVING_TEAM_PICK = 'ADD_GIVING_TEAM_PICK';
export const ADD_RECEIVING_TEAM_PICK = 'ADD_RECEIVING_TEAM_PICK';
export const ADD_TRADE_MESSAGE = 'ADD_TRADE_MESSAGE';
export const REMOVE_GIVING_TEAM_PICK = 'REMOVE_GIVING_TEAM_PICK';
export const REMOVE_RECEIVING_TEAM_PICK = 'REMOVE_RECEIVING_TEAM_PICK';
export const CLEAR_RECEIVING_TEAM = 'CLEAR_RECEIVING_TEAM';
export const CLEAR_TRADE = 'CLEAR_TRADE';
export const SAVE_TRADE = 'SAVE_TRADE';
export const LOAD_TRADE = 'LOAD_TRADE';
export const PROPOSED_TRADE = 'PROPOSED_TRADE';
export const REJECTED_TRADE = 'REJECTED_TRADE';
export const WITHDRAWN_TRADE = 'WITHDRAWN_TRADE';
export const ACCEPTED_TRADE = 'ACCEPTED_TRADE';
export const RECEIVE_ACCEPTED_TRADES = 'RECEIVE_ACCEPTED_TRADES';

// watchlists
export const RECEIVE_WATCHLIST = 'RECEIVE_WATCHLIST';
export const ADDED_TO_WATCHLIST = 'ADDED_TO_WATCHLIST';
export const REMOVED_FROM_WATCHLIST = 'REMOVED_FROM_WATCHLIST';
